# Generated by Django 4.1.1 on 2022-10-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_csvfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_ID', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Customer_type', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Product_line', models.CharField(max_length=200)),
                ('Unit_price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Tax_5pct', models.FloatField()),
                ('Total', models.FloatField()),
                ('Date', models.CharField(max_length=200)),
                ('Time', models.CharField(max_length=200)),
                ('Payment', models.CharField(max_length=200)),
                ('cogs', models.FloatField()),
                ('gross_margin_percentage', models.FloatField()),
                ('gross_income', models.FloatField()),
                ('Rating', models.FloatField()),
            ],
        ),
    ]
